name: test

on:
  push:
    branches: ['master']
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16.14.2
        cache: npm
    - name: Install dependencies
      run: npm install

    - name: Install ci
      run: npm ci

    - name: Run fav comics
      run: npm run test
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        GIT_USER: ${{ secrets.GIT_USER }}
        GIT_REPO: ${{ secrets.GIT_REPO }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID}}